In [7]:
import pandas as pd
import numpy as np

In [11]:
df = pd.read_csv('csv/act1.csv')
df

  Sucursal Vendedor  Ventas_Q1  Ventas_Q2
0    Norte      Ana      15000      16500
1      Sur     Luis      12000      11500
2    Norte      Ana      18000      19000
3     Este    Pedro       9000      10000
4      Sur     Luis      11000      10500
5     Este    Marta      20000      21000
6    Norte    Elena      14000      15000
7      Sur    Marta      16000      17500

In [12]:
media_q1 = np.mean(df['Ventas_Q1'])
desv_std_q1 = np.std(df['Ventas_Q2'])

In [13]:
df['Venta_Total'] = df['Ventas_Q1'] + df['Ventas_Q2']
df['Crecimiento_%'] = ((df['Ventas_Q2'] - df['Ventas_Q1']) / df['Ventas_Q1']) * 100

In [14]:
resumen = df.groupby('Sucursal').agg({
    'Venta_Total' : ['sum','mean'],
    'Vendedor' : 'count'
}).reset_index()

In [16]:
df.head()

  Sucursal Vendedor  Ventas_Q1  Ventas_Q2  Venta_Total  Crecimiento_%
0    Norte      Ana      15000      16500        31500      10.000000
1      Sur     Luis      12000      11500        23500      -4.166667
2    Norte      Ana      18000      19000        37000       5.555556
3     Este    Pedro       9000      10000        19000      11.111111
4      Sur     Luis      11000      10500        21500      -4.545455

In [22]:
print(f'media Q1: {media_q1}')
print(f"desviacion estandar Q1: {desv_std_q1:.2f}")

media Q1: 14375.0
desviacion estandar Q1: 3838.54

In [23]:
resumen

  Sucursal Venta_Total               Vendedor
                   sum          mean    count
0     Este       60000  30000.000000        2
1    Norte       97500  32500.000000        3
2      Sur       78500  26166.666667        3